### PR TITLE
Dynamic height in useComputedHeight hook

### PR DESCRIPTION
**Pull request by olivermrbl**

### CODE REVIEW

**Review by kasperkristensen — APPROVED** [review]
LGTM, works like a charm 😄

**Comment by adrien2p** [comment]
Why dont take advantage of https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

**Comment by adrien2p** [comment]
what will be the use cases for those hooks ?

**Comment by olivermrbl** [comment]
> what will be the use cases for those hooks ?

One use case is for controlling the height of our layout panes. You can read a longer discussion thread on it [here](https://github.com/medusajs/admin/pull/234).

**Pull request merged**
