### PR TITLE
feat: variant grid on product details and creation

### PR DESCRIPTION
**Pull request by zakariaelas**
### What

- adds variant grid to product details and creation

### CODE REVIEW

**Review by olivermrbl — COMMENTED** [review]
Would it make sense to remove the Pricing card on simple products and just force the user to use the edit variant modal? @srindom @zakariaelas  

image

**Comment by srindom** [comment]
> Would it make sense to remove the Pricing card on simple products and just force the user to use the edit variant modal? @srindom @zakariaelas
> 
> image

Yes! I think that is a great idea - in the future we could introduce some sort of identifier that would make it more verbose that a product is in fact a simple product. I think the guessing game of saying that if there is only one variant it is a simple product might not play out too well.

**Review by srindom — CHANGES_REQUESTED** [review]
Let's kill the price section and then we are good to go! :)

**Comment by zakariaelas** [comment]
sounds good guys! To re-iterate, we're getting rid of the "simple product" vs "product with variants" views, and we're just going with a more generic view which will exclude the pricing card and include the variants card (+ eveything else), is that correct? @olivermrbl @srindom

**Comment by srindom** [comment]
@zakariaelas yes that is correct - the exception, however, is when creating a new product; I think that it is pretty nice that you are not forced to come up with an option and option value when you don't need it.

Also I just spotted that when creating a product with variants there is an issue with parsing the form data:
image

**Comment by zakariaelas** [comment]
@srindom couldn't get to reproduce the error, but after making some changes, tried with similar inputs and worked fine (un/fortunately). Let me know if you can trigger the error again :sweat_smile:

**Review by srindom — APPROVED** [review]

**Pull request merged**
