### PR TITLE
chore: Move VariantGrid to templates

### PR DESCRIPTION
**Pull request by djgovani**
**What**

- Component which is used but not grouped according to the components structure of the folder

**How**

- Move components/variant-grid to templates
- Update imports

Closes https://github.com/medusajs/admin/issues/576

### CODE REVIEW

**Comment by kasperkristensen** [comment]
Hi @djgovani,

Thank you for your contribution, and sorry for the time to respond.

The `VariantGrid` is being removed in an upcoming release, so I will be closing this PR as it is no longer needed.

**Comment by djgovani** [comment]
Hi @kasperkristensen thank you for responding. Can you please close the issue https://github.com/medusajs/admin/issues/576?

Also https://github.com/medusajs/admin/issues/575 and https://github.com/medusajs/admin/issues/574 will be there or removed in upcoming releases? If It'll be there I can move those folder as mentioned.

**Comment by kasperkristensen** [comment]
@djgovani It will be closed automatically when the PR that deletes the VariantGrid is merged 😄 

No those components still need to be moved, so you are more than welcome to open a new PR that resolves those particular issues.

**Comment by djgovani** [comment]
@kasperkristensen got it. I have opened a PR for both the issues to move components to atoms.

**Pull request closed without merging**
