### PR TITLE
Fix: the UI issue on the settings page card

### PR DESCRIPTION
**Pull request by ymaheshwari1**
**What changes are in the PR?**
Added h-full class to the setting card button

**Why these changes are relevant?**
To have good and consistent UI

**How have the changes been implemented?**
Added height 100%

 **How has the changes been tested or how can the reviewer test the feature?**
Tested the changes on frontend, and you can verify it by redirecting to the settings page

Before:
image

After:
Screenshot (167)

### CODE REVIEW

**Comment by olivermrbl** [comment]
Thanks @ymaheshwari1 ! Appreciate it 💜

**Review by olivermrbl — APPROVED** [review]

**Review by olivermrbl — CHANGES_REQUESTED** [review]
Can I get you to create a new PR with develop as base branch? :)

**Comment by ymaheshwari1** [comment]
> Can I get you to create a new PR with develop as base branch? :)

Sure, @olivermrbl  should I always create PR from develop?

**Comment by ymaheshwari1** [comment]
Closing as handled in #337

**Pull request closed without merging**
