### PR TITLE
Feat/product collection images

### PR DESCRIPTION
**Pull request by edihasaj**

### CODE REVIEW

**Comment by edihasaj** [comment]
Screenshot 2022-10-22 2247115

**Comment by edihasaj** [comment]
Screenshot 2022-10-23 000153

**Comment by Thisisjuke** [comment]
Hey @edihasaj !
Is this feature discussed and is it planned to be merge ?

**Comment by edihasaj** [comment]
I think yes, I am waiting for the core to get merged first

**Pull request closed without merging**
