### PR TITLE
Fix: Remove metadata on collections

### PR DESCRIPTION
**Pull request by pKorsholm**
**What**
- include overrides of metadata with null

### CODE REVIEW

**Review by srindom — APPROVED** [review]
LGTM

**Comment by srindom** [comment]
This is quite old, but think it is a nice addition; should we merge?

cc: @olivermrbl

**Comment by olivermrbl** [comment]
Sure, but I'd like @kasperkristensen to sign off on all admin PRs while he's working on RHF to avoid introducing conflicts 💪

**Comment by kasperkristensen** [comment]
LGTM me, and no issue with the RHF PR 😄 @olivermrbl

**Pull request merged**
