### PR TITLE
feat: Settings overview

### PR DESCRIPTION
**Pull request by kasperkristensen**
**What**

- Adds settings card component
- Adds several icons from the new design system
- Adds Settings Overview template

**Also**
- Added a minimum margin on the body on large screens as only having mx-auto resulted in the settings cards to fill the entire screen from the sidebar to the right on screen widths 1500-1700px.

**Note**

- Spacing is still not right due to layout.css and login-layout/layout.css specifying a default font size of 23px. To view the PR with proper spacing out comment those files.

### CODE REVIEW

**Comment by olivermrbl** [comment]
The page layout PR has been merged. You can now rebase off of `feat/revamp` @kasperkristensen  :)

**Comment by olivermrbl** [comment]
It looks like the last couple of commits have tampered with the layout of the settings cards @kasperkristensen 
image

**Comment by kasperkristensen** [comment]
@olivermrbl just pushed a fix :)

**Review by olivermrbl — APPROVED** [review]
Great work!

**Pull request merged**
